### Test Chat
POST http://localhost:4000/chat-gemini/message
content-type: application/json

{
  "message": "cómo me llamo?"
}

### Test Embedding
POST http://localhost:4000/embedding-gemini/text
content-type: application/json

{
  "collectionName": "sobre_mi",
  "documentTitle": "Qué cosas como",
  "text": "Generalmente como muchas verduras. Soy vegetariano, así que no como carnes de ningún tipo, aunque sí pescado. Me gusta de todo: fideos, arroz, sopas, frutas, verduras. Todo excepto las habas y un par de cosas más. "
}

### Test Query
POST http://localhost:4000/embedding-gemini/query
content-type: application/json

{
  "collectionName": "sobre_mi",
  "resultNumber": 1,
  "query": "cómo me llamo?"
}

### List collections
GET http://localhost:4000/embedding-gemini/collections

### List documents
GET http://localhost:4000/embedding-gemini/collections/sobre_mi/documents

### Test Create Collection
POST http://localhost:4000/embedding-gemini/collections
content-type: application/json

{
  "name": "miaaa",
  "description": 123
}


